/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2022-05-08 14:12:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class baksin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1652010805556L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1652010955650L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ResultSet rs = null;
	PreparedStatement pstmt = null;
	request.setCharacterEncoding("utf-8");
	try{
		Class.forName("oracle.jdbc.OracleDriver");
		Connection con = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "system", "1234");
		request.setCharacterEncoding("utf-8");
		String sql = "select pname, jumin, decode(substr(jumin,8,1), '1', '남자','2','여자'), tel, substr(RESVDATE,1,4) || '년' || substr(RESVDATE,5,2) || '월' || substr(RESVDATE,7,2) || '일', substr(RESVTIME,1,2) || '-' || substr(RESVTIME,3,2), HOSPNAME,HOSPTEL,HOSPADDR, decode(VCODE,'V001','A백신','V002','B백신','V003','C백신') from tbl_jumin_201808 tj natural join TBL_VACCRESV_202108 tv join  tbl_hosp_202108 tp on tv.HOSPCODE = tp.HOSPCODE where RESVNO= ?";
		pstmt = con.prepareStatement(sql);
		pstmt.setString(1, request.getParameter("num"));
		rs = pstmt.executeQuery();
	}catch(Exception e){
		e.printStackTrace();
	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("	<h2>(과정평가형 정보처리산업기사) 백신접종예약 프로그램 ver 2021-08</h2>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<div><a href=\"insert.jsp\">백신접종예약</a></div>\r\n");
      out.write("		<div><a href=\"baksinSelect.jsp\">접종예약조회</a></div>\r\n");
      out.write("		<div><a href=\"select.jsp\">접종인원통계</a></div>\r\n");
      out.write("		<div><a href=\"index.jsp\">홈으로</a></div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
 if(rs.next()){ 
      out.write("	\r\n");
      out.write("<h2 class=\"title\">예약번호 : ");
      out.print(request.getParameter("num") );
      out.write("의 접종예약조회</h2>\r\n");
      out.write("<table border=\"1px\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>이름</td>\r\n");
      out.write("	<td>주민번호</td>\r\n");
      out.write("	<td>전화번호</td>\r\n");
      out.write("	<td>예약일자</td>\r\n");
      out.write("	<td>예약시간</td>\r\n");
      out.write("	<td>병원명</td>\r\n");
      out.write("	<td>대표전화</td>\r\n");
      out.write("	<td>병원주소</td>\r\n");
      out.write("	<td>백신종류</td>\r\n");
      out.write("</tr>\r\n");
      out.write("	");
do{ 
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(8) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(9) );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	<button style=\"margin: 0 auto; display: flex\"><a style=\"text-align: center;\" href=\"index.jsp\">돌아가기</a></button>\r\n");
      out.write("	");
}while(rs.next()); 
      out.write("\r\n");
      out.write("\r\n");
}else{ 
      out.write("\r\n");
      out.write("	<h2 class=\"title\">접종예약정보가 존재하지 않습니다!</h2>\r\n");
      out.write("	<button style=\"margin: 0 auto; display: flex\"><a style=\"text-align: center;\" href=\"index.jsp\">돌아가기</a></button>\r\n");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      out.write("	<div>HRDKOREA Copyright @ 2021 All rights reserved. Human Resources Development Service of Korea</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
